smallbankArgs: &smallbank-args
  accounts: 100
  txnPerBatch: 1

rateControl: &rate
  type: fixed-rate
  opts:
    tps: 350

test:
  name: smallbank
  description: Smallbank benchmark for evaluating create, modify, and query operations.
  workers:
    type: local
    number: 5
  rounds:
    - label: create
      txNumber: 1000
      rateControl: *rate
      workload:
        module: benchmarks/scenario/smallbank/create.js
        arguments: *smallbank-args
monitors:
    resource:
    - module: docker
      options:
        interval: 1
        containers: ['all']
